      SUBROUTINE DEFINE
*
*
*       Definition of input parameters, options & counters.
*       ---------------------------------------------------
*
*
*       Input parameters
*       ****************
*
*       ---------------------------------------------------------------------
***
* NBODY6:
*
*       KSTART  Control index (1: new run; >1: restart; 3, 4, 5: new params).
*       TCOMP   Maximum CPU time in minutes (saved in CPU).
*       TCRITP  Termination time in Myrs.
*       isernb  Max size of sequential irr blocks on parallel machine 
*       iserreg as isernb for reg blocks
*       iserks  as isernb for KS blocks
***
* INPUT:
*
*       N       number of objects (stars, remnants), including singles and 
*               members of binaries, multiples (N_s + N_b; singles + 3*NBIN0 < NMAX).
*       NFIX    Output frequency of data save or binaries
*               (output every DELTAT*NFIX time step; used in #3 & #6).
*       NCRIT   Final particle number (alternative termination criterion).
*       NRAND   Random number sequence skip.
*       NNBMAX  Maximum number of neighbours (< LMAX - 5).
*       NRUN    Run identification index.
*
*       ETAI    Time-step parameter for irregular force polynomial.
*       ETAR    Time-step parameter for regular force polynomial.
*       RS0     Initial radius of neighbour sphere (N-body units).
*       DTADJ   Time interval for parameter adjustment (N-body units).
*       DELTAT  Output time interval (N-body units).
*       TCRIT   Termination time (N-body units).
*       QE      Energy tolerance (restart if DE/E > 5*QE & #2 > 1).
*       RBAR    Virial cluster radius in pc (set = 1 for isolated cluster).
*       ZMBAR   Mean mass in solar units (=1.0 if <=0; final depends on #20).
*
*       KZ(J)   Non-zero options for alternative paths
*               (see table, here KZ(1) - KZ(50) also shown as #1 - #50).
*
*       DTMIN   Time-step criterion for regularization search.
*       RMIN    Distance criterion for regularization search.
*       ETAU    Regularized time-step parameter (6.28/ETAU steps/orbit).
*       ECLOSE  Binding energy per unit mass for hard binary (positive).
*       GMIN    Relative two-body perturbation for unperturbed motion.
*       GMAX    Secondary termination parameter for soft KS binaries.
*       SMAX    Maximum time-step (factor of 2 commensurate with 1.0).
***
* INPUT: if (kz(4).gt.0) (suppressed now)
*
*       DELTAS  Output interval for binary search (in TCR; suppressed).
*       ORBITS  Minimum periods for binary output (level 1).
*       GPRINT  Perturbation thresholds for binary output (9 levels).
***
* DATA:
*
*       ALPHAS  Power-law index for initial mass function (used if #20 < 2).
*       BODY1   Maximum particle mass before scaling (#20: solar mass).
*       BODYN   Minimum particle mass before scaling.
*       NBIN0   Number of primordial binaries (for IMF2 with #20 > 1).
*       NHI0    Primordial hierarchies (may be needed in IMF if > 0).
*       ZMET    Metal abundance (in range 0.03 - 0.0001).
*       EPOCH0  Evolutionary epoch (in 10**6 yrs; NB! < 0 for PM evolution).
*       DTPLOT  Plotting interval for stellar evolution HRDIAG (N-body units; >= DELTAT).
***
* SETUP: if (kz(5).eq.2)
*
*       APO     Separation of two Plummer models in Nbody Unit (SEMI = APO/(1 + ECC).
*               (Notice SEMI will be limited between 2.0 to 50.0)
*       ECC     Eccentricity of two-body orbit (ECC >=0 and ECC < 0.999).
*       N2      Membership of second Plummer model (N2 <= N).
*       SCALE   Scale factor for the second Plummer model,
*               second cluster will be generated by first Plummer model with X*SCALE and V*SQRT(SCALE),
*               (>= 0.2 for limiting minimum size).
*
*        if (kz(5).eq.3)
*
*       APO     Separation between the perturber and Sun in Nbody Unit.
*       ECC     Eccentricity of orbit (=1 for parabolic encounter).
*       SCALE   Perturber mass scale factor, perturmer mass = Center star mass * SCALE (=1 for Msun).
*
*        if (kz(5).eq.4)
*
*       SEMI    Semi-major axis (slightly modified; ignore if ECC > 1).
*       ECC     Eccentricity (ECC > 1: NAME = 1 & 2 free-floating).
*       M1      Mass of first member (in units of mean mass).
*       M2      Mass of second member (rescaled total mass = 1).
*
*        if (kz(5).ge.6) & (kz(24).lt.0)
*
*       ZMH     Mass of single BH (in N-body units).
*       RCUT    Radial cutoff in Zhao cusp distribution (MNRAS, 278, 488).
***
* SCALE:
*
*       Q       Virial ratio (Q = 0.5 for equilibrium).
*       VXROT   XY-velocity scaling factor (> 0 for solid-body rotation).
*       VZROT   Z-velocity scaling factor (not used if VXROT = 0).
*       RTIDE   Unscaled tidal radius (#14 >= 2; otherwise copied to RSPH2).
*               (#23 >=3, RTIDE will be devided by scaling factor)
***
* XTRNL0: if (kz(14).eq.2)
*
*       GMG     Point-mass galaxy (solar masses, linearized circular orbit).
*       RG0     Central distance (in kpc).
*
*         if (kz(14).eq.3)
*
*       GMG     Point-mass galaxy (solar masses).
*       DISK    Mass of Miyamoto disk (solar masses).
*       A       Softening length in Miyamoto potential (in kpc).
*       B       Vertical softening length (kpc).
*       VCIRC   Galactic circular velocity (km/sec) at RCIRC (=0: no halo).
*       RCIRC   Central distance for VCIRC with logarithmic potential (kpc).
*       RG      Initial position; DISK+VCIRC=0, VG(3)=0: A(1+E)=RG(1), E=RG(2).
*       VG      Initial cluster velocity vector (km/sec).
*
*         if (kz(14).eq.3.or.kz(14).eq.4)
*
*       MP      Total mass of Plummer sphere (in scaled units).
*       AP      Plummer scale factor (N-body units; square saved in AP2).
*       MPDOT   Decay time for gas expulsion (MP = MP0/(1 + MPDOT*(T-TD)).
*       TDELAY  Delay time for starting gas expulsion (T > TDELAY).
***
* BINPOP: if (kz(8).eq.1.or.kz(8).gt.2) 
*
*       SEMI    Initial semi-major axis limit
*       ECC     Initial eccentricity (for BINPOP_4NEW)
*               <=1 AND >=0 for one particular fixed ecc. for all systems
*               < 0 for thermal distribution,
*               =20 for uniform distribution,
*               =30 for f(e)=0.1765/(e*e)
*               =40 for general f(e)=a*e^b, e0<=e<=1 with a=(1+b)/(1-e0^(1+b))
*                   e0 and b must be defined in binpop routine
*       RATIO   Mass ratio M1/(M1 + M2); (= 1.0: M1 = M2 = <M>).
*       RANGE   #42= 0: semi-major axis range for uniform logarithmic distribution.
*               #42= 6: Minimum period of binary in unit of day.
*       NSKIP   Binary frequency of mass spectrum (starting from body #1).
*       IDORM   Indicator for dormant binaries (>0: merged components).
***
* HIPOP: if (kz(8).gt.0.and.kz(18).gt.1)
*
*       SEMI    Max semi-major axis in model units (all equal if RANGE = 0).
*       ECC     Initial eccentricity (< 0 for thermal distribution).
*       RATIO   Mass ratio (= 1.0: M1 = M2; random in [0.5-0.9]).
*       RANGE   Range in SEMI for uniform logarithmic distribution (> 0).
***
* IMBHINIT: if (kz(24).eq.1) 
*
*       MMBH     Mass of massive black hole in unit solar mass
*       XBH(1:3) 3 dimensional position of massive black hole in unit pc.
*       VBH(1:3) 3 dimensional velocity of massive black hole in km/s.
*       DTBH     Output interval for massive black hole data in mbh.45 and mbhnb.46 (NB unit)
*
***
* INTIDE: if (kz(27).gt.0)  (currently suppressed)
*
*       RSTAR   Size of typical star in A.U.
*       IMS     # idealized main-sequence stars.
*       IEV     # idealized evolved stars.
*       RMS     Scale factor for main-sequence radii (>0: fudge factor).
*       REV     Scale factor for evolved radii (initial size RSTAR).
***
* CLOUD0: if (kz(13).gt.0)
*
*       NCL     Number of interstellar clouds.
*       RB2     Radius of cloud boundary in pc (square is saved).
*       VCL     Mean cloud velocity in km/sec.
*       SIGMA   Velocity dispersion (#13 > 1: Gaussian).
*       CLM     Individual cloud masses in solar masses (maximum MCL).
*       RCL2    Half-mass radii of clouds in pc (square is saved).
*       ---------------------------------------------------------------------
*
*
*       Options KZ(J)
*       *************
*
*       ---------------------------------------------------------------------
*       1  COMMON save to fort.1 for restart
*                =0: No save      
*                =1: save when touch file named 'STOP';
*                =2: every 100*NMAX steps.
*       2  COMMON save to fort.2 for restart
*                =0: No save      
*                =1: save at output time;
*                =2: save at output time and automatically restart
*                    if DE/E > 5*QE.
*       3  Basic data conf.3_* (snapshot files splited by time at output time):
*                    First line:   NTOT, MODEL, NRUN, NK
*                    Second line:  time, Scaling factor, density center, core
*                                  properties, half mass radius ...
*                    Main content: mass, rhos, xns, x, v, phi, name;
*                                  (in Nbody Unit; unformatted binary file)
*                =0: No output.
*               >=1: output with frequencey NFIX (output.F)
*       4  (suppressed now) Binary diagnostics on unit 4 (# threshold levels = #4 < 10).
*       5  Initial conditions (Need #22 =0);
*                =0: uniform & isotropic sphere;
*                =1: Plummer model;
*                =2: two Plummer models in orbit, extra input;
*                =3: massive perturber and planetesimal disk
*                   (each pariticle has circular orbit, constant separation along radial 
*                    direction between each neighbors and random phase), extra input;
*                =4: massive initial binary, extra input: A, E, M1, M2;
*                =5: Jaffe model;
*               >=6: Zhao BH cusp model, extra input if #24 < 0: ZMH, RCUT.
*       6  Significant & regularized binaries at main output (bodies.f):
*                =0: No output
*                =1: Both soft and regularized binaries
*                =2: Only regularized binaries
*                =3: Print soft binaries with frequency NFIX and regularized
*                    binaries with each output step
*                =4: Print soft binaries and regularized binaries with
*                    frequency NFIX.
*       7  Lagrangian radii, average mass, particle counters, average velocity,
*          velocity dispersion, rotational velocity within shells (lagr.f);
*          (Notice the total mass to calculate Lagrangian radii is fixed to the
*           initial total mass of cluster)
*                =0: No calculation and output      
*                =1: Get actual value of half mass radius RSCALE (use current total mass),
*                    no output
*               >=2: Output data at main output and lagr.7
*               >=6: Lagrangian radii for two mass groups on unit 31 & 32,
*                    based on #5=1,2 (slowly: O(N^2), lagr2.f)
*          -- Method:
*              =2,4: Lagrangian radii calculated by initial cluster mass
*            =3,>=5: Lagrangian radii calculated by current cluster mass 
*                   (The only single/binary stars Lagrangian radii are still 
*                    calculated by initial single/binary total mass)
*              =2,3: All parameters are averaged within Lagrangian shells
*               >=4: All parameters are averaged from center to each Lagrangian radius
*       8  Primordial binaries initialization and output:
*          -- Initialization:
*                =0: No primordial binaries      
*            =1,>=3: generate primordial binaries based on #41,42 (binpop.F);
*                =2: input primordial binaries from first 2*NBIN0 lines of dat.10;
*          -- Output:      
*                >0: Save information of primordial binary that change member in pbin.18.
*                    binary diagnostics at main output (binout.f) 
*               >=2: output KS bianry in bdat.9_*, soft binary in bwdat.19_*.
*                    These two kind of snapshot files are splited by time. Here '*' is time. (bindat.f)
*       9  Binary diagnostics
*                =0: No output
*              =1,3: Diagnostics for the hardest binary below ECLOSE in hbin.39 (adjust.F)
*               >=2: Binary evolution output in binev.17 (binev.f)
*               >=3: Binary with degenerate stars in degen.4 (degen.f)
*      10  KS regularization diagnostics at main output
*                =0: No output      
*               >=1: Output new KS information;
*               >=2: Output end KS information;
*               >=3: Output each integrating step information.
*      12  HR diagnostics of evolving stars output with time interval DTPLOT (hrplot.F).
*                =0: No output
*                >0: Output single stellar evolution in sse.83_*;
*                    output regularized binary steller evolution in bse.82_*;
*                    These two kind of snapshot files are splitted by time. Here '*' is time.
*      13  Interstellar clouds
*                =1: constant velocity;
*               >=2: Gaussian.
*      14  External tidal force:
*                =0: No tidal field      
*                =1: standard solar neighbor tidal field
*                =2: point-mass galaxy with circular orbit (extra input)
*                =3: point-mass + disk + halo + Plummer (extra input)
*                =4: Plummer model (extra input)
*      15  Triple, quad, chain or merger search:
*                =0: Switch off all >3 bodies multiple-regulization methods
*               >=1: Switch on triple, quad, chain(#30>0) and merger search (impact.f)
*               >=2: Diagnostics at main output at begin and end of triple, quad regulization.
*               >=3: Save first five outer orbits every half period of wide quadruple before merger
*                    and stable quadruples that accepted for merger in quastab.89
*      16  Automatical updating of regularization parameters:
*                =0: Use input values and no update
*               >=1: Adjust RMIN, DTMIN & ECLOSE every DTADJ time
*               >=3: modify RMIN for GPERT > 0.05 or < 0.002 in chain. output diagnostics at kscrit.77
*      17  Automatical updating of ETAI, ETAR and ETAU by tolerance QE (check.f) every DTADJ time
*                =0: Use input values and no update
*               >=1: Adjust ETAI, ETAR 
*               >=2: Adjust ETAU 
*      18  Hierarchical systems:
*                =0: No diagnostics and primordial triples      
*              =1,3: diagnostics (hiarch.f);
*               >=2: Initialize primordial stable triples, number is NHI0 (hipop.F);
*               >=4: Hierarchical data of stable triple, quad... in hidat.87_*, snapshot files are
*                    splitted by time (here * is time in Nbody Unit) (hidat.f);
*      19  Stellar evolution mass loss
*              =1,2: old supernova scheme;
*               >=3: Eggleton, Tout & Hurley;
*               >=5: extra diagnostics. (mdot.F)
*          -- Initial EPCHO
*              =2,4: Input stellar parameters from fort.21 (instar.f)
*                    N lines of (MI, KW, M0, EPOCH1, OSPIN)
*                      MI: Current mass
*                      KW: Kstar type
*                      M0: Initial mass
*                      EPOCH1: evolved age of star(Age = TIME[Myr] - EPOCH1)
*                      OSPIN: angular velocity of star
*      20  Initial mass function (Need #22 =0 or 9);
*                =0: Salpeter type power-law mass function using ALPHAS (data.F)
*                =1: Miller-Scalo-(1979)IMF (imf.f)
*              =2,4: Kroupa(1993) (3-components) (imf2.f)
*              =3,5: Eggleton-IMF (book) (imf2.f)
*              =6,7: Kroupa(2001) (imf2.f) extended to Brown Dwarf regime(imfbd.f)
*          -- Primordial binary mass:
*              =2,6: random pairing (imf2.f)
*          =3,4,5,7: correlation (m1/m2)' = (m1/m2)**0.4 & constant sum (Eggleton).(imf2.f)
*      21  Extra diagnostics information at main output every DELTAT interval (output.F)
*                =0: No extra output      
*               >=1: NRUN, MODEL, TCOMP, TRC, DMIN, AMIN, RMAX, RSMIN, NEFF
*               >=2: Number of escapers NESC at main output will be counted
*                    by Jacobi escape criterion (slowly: O(N^2), jacobi.f)
*      22  Initialization of basic particle data mass, position and velocity (data.F):
*          -- Initialization with internal method:
*              =0,1: generate initial position and velocity based on #5;
*                    generate initial mass based on #20.
*                =1: Save initial mass, position and velocity into dat.10.
*          -- Initialization with input data from dat.10:
*             =2->5: Input data with Nbody-Unit (no scaling treatment after reading data)
*             =6->9: Input data with Non-scaling (will do scaling after reading data);
*          ---- Format:
*              =2,6: standard nbody input format (7 parameters each line: m,r,v);
*              =3,7: tree format (N, 2*DUMMY, MASS(1->N), position(1->N), velocity(1->N))
*              =4,8: starlab input format
*                =9: same as =6, but ignore input mass, use IMF based on #20.
*      23  Escaper removal (escape.f):
*                =0: No escaper removal
*               >=1: Remove escaper and ghost particles generated by collision
*              =2,4: Save escaper diagnostics information in esc.11;
*               >=3: initialization & integration of tidal tail.
*      24  Initial conditions for subsystem
*                <0: ZMH & RCUT (N-body units) Zhao model (Need #5>=6).
*                =1: Add one massive black hole (extra input: mass, position, velocity and 
*                    output frequency), will output black hole data in 
*      25  Velocity kicks for white dwarfs (kick.F)
*                =0: No kick of WDs
*                =1: type 10 Helium white dwarf & 11 Carbon-Oxygen white dwarf
*                =2: all WDs (type 10,11 and type 12 Oxygen-Neon white dwarf)
*          (suppressed now) Partial reflection of KS binary orbit (GAMMA < GMIN) (ksint.f)
*      26  Slow-down of two-body motion, which will increase the regularization computing speed
*               >=1: Apply to KS
*               >=2: Apply to chain
*                =3: rectify to get better energy conservation
*      27  Two-body tidal circularization (Mardling & Aarseth, 2001; Portegies Zwart et al. 1997) 
*          (Please suppress in KS parallel version) 
*                =1: sequential;
*                =2: chaos;
*                =3: GR energy loss
*               =-1: collision detector, suppress coalescence
*      28  Magnetic braking and gravitational radiation for NS & BH binaries
*          (Need #19 = 3; based on #27);
*                =0: No effect
*               >=1: GR coalescence for NS & BH (brake.f, brake3.f)
*               >=2: Diagnostics at main output (brake.f)
*                =3: Input of ZMH = 1/SQRT(2*N) (Need #5 >= 6) (setup.F)
*                =4: Make every star type 13 Neutron star (Need #27 = 3) (instar.f) 
*      29  Boundary reflection for hot system.
*      30  Multiple regularization:
*               =-1: Use chain only;
*                =0: No triple, quad and chain regularization, only merger.
*                =1: Switch on triple, quad and chain (impact.f);
*               >=2: Diagnostics at begin/end of chain at main output;
*               >=3: Diagnostics at each step of chain at main output;
*      31  Centre of mass correction after energy check. (cmcorr.f)
*      32  Adjustment(increase) of adjust interval DTADJ, output intervals DELTAT
*          and enegry error criterion QE based on single particle energy (check.f)
*      33  Block-step level histograms diagnostics at main output
*               >=1: Output irregular block step;
*                    primordial binaries step (need #8>0 or NBIN0>0)
*               >=2: Output regular block step;
*      34  Roche-lobe overflow
*                =0: No Roche
*                =1: Roche & Spin synchronisation on binary with circular orbit (synch.f)
*                =2: Roche & Tidal synchronisation on binary with circular orbit by BSE method (bsetid.f)
*      35  Time offset control, if switch on TIME will be reset to zero every 100 time units.
*          Global time is TTOT = TIME + TOFF (adjust.F)
*      36  (suppressed now) Step reduction for hierarchical systems 
*      37  Neighbour list additions (checkl.F)
*                =0: No extra modification      
*               >=1: Add high-velocity particles into neighbor list;
*               >=2: Add small time step particle (like close encounter particles near neighbor radius)
*                    into neighbor list.
*      38  Force polynomial corrections during regular block step calculation
*                =0: standard, no corrections;
*                =1: all gains & losses included;
*                =2: small FREG change skipped;
*                =3: fast neighbour loss only.
*      39  Neighbor radius adjustment method
*                =0: The system have unique density centre and smooth density profile;
*            =1,>=3: The system have no unique density centre or smooth density profile:
*                      >> will skips velocity modification of RS(I) (regint.f, regcor_gpu.f);
*                      >> will not reduce neighbor radius if particle is outside half mass radius;
*                      >> (For GPU) reduce RS(I) by multiply 0.9 instead of estimation of RS(I) 
*                      based on NNBOPT/NNB when GPU overflow happened (fpoly0.F, util_gpu.F).
*              =2,3: (For GPU) Consider sqrt(particle mass / average mass) as the factor to
*                    determine the particle's neighbor membership. (fpoly0.F, util_gpu.F)
*      41  proto-star evolution for primordial binaries initialization (proto_star_evol, binpop.F)
*                =0: No proto-star evolution
*                =1: proto-star evolution of eccentricity and period
*      42  Initial binary distribution
*                =0: RANGE>0: uniform distribution in log(semi) between SEMI0 and SEMI0/RANGE
*                    RANGE<0: uniform distribution in semi between SEMI0 and -1*RANGE.
*                =1: linearly increasing distribution function f=0.03438*logP
*                =2: f=3.5logP/[100+(logP)**2]
*                =3: f=2.3(logP-1)/[45+(logP-1)**2] This is a "3rd" iteration when
*                    pre-ms evolution is taken into account with #41=1.
*                =4: f=2.5(logP-1)/[45+(logP-1)**2] This is a "34th" iteration when
*                    pre-ms evolution is taken into account with #41=1, and
*                    RBAR<1.5 (in runs /run34n RBAR=1.5 with #42=3 lead to
*                    wrong qone distr.
*                =5: Duquennoy & Mayor 1991, Gaussian distr. 
*                    with mean logP=4.8, SDEV in logP=2.3. Use Num.Recipes
*                    routine "gasdev.f" to obtain random deviates given "idum1".
*                =6: eigen-evolution (Pavel Kroupa & Rosemary Mardling).
*      46   HDF5/CSV format output (name,time,x,v,m,f,fdot,kstar,rho,phi,L,
*                radius,Teff,m_core,radius_core)
*              =1,3: HDF5 format
*              =2,4: CSV format
*              =1-2: Only output active stars with time interval defined by #47
*              =3-4: Output full particle list with time interval defined by #47
*      47   Frequency for #46 output
*                =0: Output data during each irregular block time step
*              1-63: Output data with time interval 0.5**(#47)
*      49   Computation of Moments of Inertia (with Chr. Theis) in fort.60 (ellan.f)
*                    
*      4,11,24,36,40,43-45,48,50  Currently free.
*       ---------------------------------------------------------------------
*
* NBODY6: Restart from fort.1
*
*       KSTART TCOMP TCRITP isernb iserreg iserks (KSTART = 2, 3, 4, 5)
*
*       DTADJ DELTAT TADJ TNEXT TCRIT QE J KZ(J) (if > 0 & KSTART = 3 or 5).
*       
*       ETAI ETAR ETAU DTMIN RMIN NCRIT NNBOPT SMAX(if > 0 & KSTART = 4 or 5).
*
*       ---------------------------------------------------------------------
*
*       Output counters
*       ***************
*
*       ---------------------------------------------------------------------
*       NSTEPI  Irregular integration steps.
*       NSTEPR  Regular integration steps.
*       NSTEPU  Regularized integration steps.
*       NNPRED  Coordinate & velocity predictions of all particles.
*       NBPRED  Coordinate & velocity prediction of neighbours (NNB counted).
*       NBCORR  Force polynomial corrections.
*       NBFULL  Too many neighbours with standard criterion.
*       NBVOID  No neighbours inside 1.26 times the basic sphere radius.
*       NICONV  Irregular step reduction (force convergence test).
*       NBSMIN  Retained neighbours inside 2*RS (STEP < SMIN).
*       NLSMIN  Small step neighbours selected from other neighbour lists.
*       NBDIS   Second component of recent KS pair added as neighbour (#18).
*       NBDIS2  Second component of old KS pair added as neighbour (#18 > 1).
*       NCMDER  C.m. values for force derivatives of KS component.
*       NBDER   Large F3DOT corrections not included in D3 & D3R.
*       NFAST   Fast particles included in LISTV (option 18).
*       NBFAST  Fast particles included in neighbour list (option 18).
*       NBLOCK  Number of blocks (block-step version).
*       NMDOT   Mass loss events (option 19).
*       NBSTAT  Diagnostic data on binary interactions (option 4).
*       NKSTRY  Two-body regularization attempts.
*       NKSREG  Total KS regularizations.
*       NEWKS   Enforced KS regularization using wider criterion (~8 > 0).
*       NKSHYP  Hyperbolic KS regularizations.
*       NKSPER  Unperturbed KS binary orbits.
*       NPRECT  Initialization of NKSPER after exceeding 2*10**9.
*       NKSREF  Partial reflections of KS binary (option 25; suppressed).
*       NKSMOD  Slow KS motion restarts (option 26).
*       NTTRY   Search for triple, quad & chain regularization or mergers.
*       NTRIP   Three-body regularizations (option 15).
*       NQUAD   Four-body regularizations (option 15).
*       NCHAIN  Chain regularizations (options 15 & 30).
*       NMERG   Mergers of stable triples or quadruples (option 15).
*       NEWHI   New hierarchical systems (counted by routine HIARCH).
*       NSTEPT  Triple regularization integration steps (option 15).
*       NSTEPQ  Quadruple regularization integration steps (option 15).
*       NSTEPC  Chain regularization steps (# DIFSY calls).
*       NDISS   Tidal dissipations at pericentre (option 27).
*       NTIDE   Tidal captures from hyperbolic motion (option 27).
*       NSYNC   Number of synchronous binaries (option 27).
*       NCOLL   Stellar collisions (option 27).
*       NSESC   Escaped single particles (option 23).
*       NBESC   Escaped binaries (option 23).
*       NMESC   Escaped mergers (options 15 & 23).
*       NRG     Red giants.
*       NHE     Helium stars.
*       NRS     Red supergiants.
*       NNH     Naked Helium stars.
*       NWD     White dwarfs.
*       NSN     Neutron stars.
*       NBH     Black holes.
*       NBS     Blue stragglers.
*       ---------------------------------------------------------------------
*
*
*       Stellar evolution types
*       ***********************
*
*       ---------------------------------------------------------------------
*       0       Low main sequence (M < 0.7).
*       1       Main sequence.
*       2       Hertzsprung gap (HG).
*       3       Red giant.
*       4       Core Helium burning.
*       5       First AGB.
*       6       Second AGB.
*       7       Helium main sequence.
*       8       Helium HG.
*       9       Helium GB.
*      10       Helium white dwarf.
*      11       Carbon-Oxygen white dwarf.
*      12       Oxygen-Neon white dwarf.
*      13       Neutron star.
*      14       Black hole.
*      15       Massless supernova remnant.
*       ---------------------------------------------------------------------
*
*       Binary types
*       ************
*
*       ---------------------------------------------------------------------
*       0       Standard case.
*      -1       Chaotic orbit (option 27 = 2).
*      -2       Circularizing (option 27 = 2).
*       9       Sequential circularization.
*      10       Circularized.
*      11       First Roche stage (option 34 =1/2).
*      12       End of first Roche stage.
*      13       Start of second Roche stage.
*      xx       Further Roche stages.
*       ---------------------------------------------------------------------
      RETURN
*
      END
